apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate  


