apiVersion: v1
kind: Service
metadata:
  name: extern-cluster-svc
spec:
  selector:
    app: myapp-mongoexpress
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 8081
      nodePort: 30000