apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongo-express
  labels:
    app: my-mongo-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-mongoexpress
  template:
    metadata:
      name: mongoexpress
      labels:
      # (**)
        app: myapp-mongoexpress
    spec:
      containers:
        - name: mongoexpress-cont
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          # This could be the mongodb container name , but in this case i suppose
          # it will be the service we have just created.
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config-mongo
                  key: db_url
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-mongo
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
              valueFrom:
                secretKeyRef:
                  name: secret-mongo
                  key: password_user
