apiVersion: v1
kind: Service
metadata:
  name: intern-cluster-svc
spec:
# This selector makes references to (**)
  selector:
    app: myapp-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017